version: '3.8'

services:
  bash:
    build: .
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  web:
    build: .
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
